# Generated by Django 6.0 on 2026-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タスク名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="詳細説明"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                (
                    "is_all_day",
                    models.BooleanField(default=True, verbose_name="終日設定"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="完了フラグ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "タスク",
                "verbose_name_plural": "タスク一覧",
            },
        ),
    ]
